//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETHF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETHF.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DbClearErrorCaption {
            get {
                return ResourceManager.GetString("DbClearErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clear database..
        /// </summary>
        internal static string DbClearErrorText {
            get {
                return ResourceManager.GetString("DbClearErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetMap: I Love You!.
        /// </summary>
        internal static string EasterEggText {
            get {
                return ResourceManager.GetString("EasterEggText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph has been drawn..
        /// </summary>
        internal static string GraphDrawCompletedTooltipText {
            get {
                return ResourceManager.GetString("GraphDrawCompletedTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MalformedURLErrorCaption {
            get {
                return ResourceManager.GetString("MalformedURLErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed URL!.
        /// </summary>
        internal static string MalformedURLErrorText {
            get {
                return ResourceManager.GetString("MalformedURLErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Error.
        /// </summary>
        internal static string SkypeErrorCaption {
            get {
                return ResourceManager.GetString("SkypeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not attach to Skype. Reason: .
        /// </summary>
        internal static string SkypeErrorText {
            get {
                return ResourceManager.GetString("SkypeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Database Error), .
        /// </summary>
        internal static string StatusObjNumErrorText {
            get {
                return ResourceManager.GetString("StatusObjNumErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  objects in database, .
        /// </summary>
        internal static string StatusObjNumText {
            get {
                return ResourceManager.GetString("StatusObjNumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  threads.
        /// </summary>
        internal static string StatusThreadNumText {
            get {
                return ResourceManager.GetString("StatusThreadNumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TargetAddErrorCaption {
            get {
                return ResourceManager.GetString("TargetAddErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add target to the databse..
        /// </summary>
        internal static string TargetAddErrorText {
            get {
                return ResourceManager.GetString("TargetAddErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Error.
        /// </summary>
        internal static string WTDbManipErrorCaption {
            get {
                return ResourceManager.GetString("WTDbManipErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database manipulation error. Shutting down thread..
        /// </summary>
        internal static string WTDbManipErrorText {
            get {
                return ResourceManager.GetString("WTDbManipErrorText", resourceCulture);
            }
        }
    }
}
